import { Game, Promotion, BettingEvent, VIPLevel } from "./types";

// Gradient colors for game thumbnails (since we can't use real images)
const GAME_COLORS = [
  "from-purple-900 to-purple-600",
  "from-blue-900 to-blue-600",
  "from-red-900 to-red-600",
  "from-green-900 to-green-600",
  "from-yellow-900 to-yellow-600",
  "from-pink-900 to-pink-600",
  "from-indigo-900 to-indigo-600",
  "from-orange-900 to-orange-600",
];

export const MOCK_GAMES: Game[] = [
  // Slots
  {
    id: "s1",
    title: "Gates of Olympus",
    provider: "Pragmatic Play",
    category: "slots",
    thumbnail: "from-purple-900 to-yellow-600",
    rtp: 96.5,
    isHot: true,
    minBet: 0.2,
    maxBet: 125,
    players: 4521,
    rating: 4.8,
    tags: ["megaways", "bonus-buy"],
  },
  {
    id: "s2",
    title: "Sweet Bonanza",
    provider: "Pragmatic Play",
    category: "slots",
    thumbnail: "from-pink-900 to-pink-400",
    rtp: 96.48,
    isHot: true,
    minBet: 0.2,
    maxBet: 100,
    players: 3892,
    rating: 4.7,
    tags: ["cluster-pays", "bonus-buy"],
  },
  {
    id: "s3",
    title: "Big Bass Bonanza",
    provider: "Pragmatic Play",
    category: "slots",
    thumbnail: "from-blue-900 to-teal-500",
    rtp: 96.71,
    isNew: true,
    minBet: 0.1,
    maxBet: 250,
    players: 2140,
    rating: 4.6,
    tags: ["fishing", "bonus"],
  },
  {
    id: "s4",
    title: "Wolf Gold",
    provider: "Pragmatic Play",
    category: "slots",
    thumbnail: "from-gray-900 to-indigo-700",
    rtp: 96.01,
    minBet: 0.25,
    maxBet: 125,
    players: 1820,
    rating: 4.5,
    tags: ["jackpot", "classic"],
  },
  {
    id: "s5",
    title: "Book of Dead",
    provider: "Play'n GO",
    category: "slots",
    thumbnail: "from-yellow-900 to-amber-600",
    rtp: 96.21,
    isHot: true,
    minBet: 0.1,
    maxBet: 100,
    players: 5230,
    rating: 4.9,
    tags: ["egypt", "expanding-wilds"],
  },
  {
    id: "s6",
    title: "Starburst",
    provider: "NetEnt",
    category: "slots",
    thumbnail: "from-indigo-900 to-purple-500",
    rtp: 96.09,
    minBet: 0.1,
    maxBet: 100,
    players: 6100,
    rating: 4.7,
    tags: ["classic", "low-variance"],
  },
  {
    id: "s7",
    title: "Reactoonz",
    provider: "Play'n GO",
    category: "slots",
    thumbnail: "from-green-900 to-lime-500",
    rtp: 96.51,
    isNew: true,
    minBet: 0.2,
    maxBet: 100,
    players: 1345,
    rating: 4.6,
    tags: ["cluster-pays", "cascading"],
  },
  {
    id: "s8",
    title: "Gonzo's Quest",
    provider: "NetEnt",
    category: "slots",
    thumbnail: "from-orange-900 to-orange-500",
    rtp: 95.97,
    minBet: 0.2,
    maxBet: 50,
    players: 2980,
    rating: 4.5,
    tags: ["avalanche", "wilds"],
  },
  {
    id: "s9",
    title: "Mega Moolah",
    provider: "Microgaming",
    category: "jackpot",
    thumbnail: "from-yellow-800 to-yellow-500",
    rtp: 88.12,
    isHot: true,
    minBet: 0.25,
    maxBet: 6.25,
    players: 8900,
    rating: 4.8,
    tags: ["progressive-jackpot", "safari"],
  },
  {
    id: "s10",
    title: "Divine Fortune",
    provider: "NetEnt",
    category: "jackpot",
    thumbnail: "from-red-900 to-pink-600",
    rtp: 96.59,
    minBet: 0.2,
    maxBet: 100,
    players: 3210,
    rating: 4.6,
    tags: ["progressive-jackpot", "greek"],
  },
  // Live Casino
  {
    id: "l1",
    title: "Lightning Roulette",
    provider: "Evolution",
    category: "live-casino",
    thumbnail: "from-yellow-900 to-yellow-600",
    rtp: 97.3,
    isLive: true,
    isHot: true,
    minBet: 1,
    maxBet: 40000,
    players: 312,
    rating: 4.9,
    tags: ["roulette", "multipliers"],
  },
  {
    id: "l2",
    title: "Infinite Blackjack",
    provider: "Evolution",
    category: "live-casino",
    thumbnail: "from-green-900 to-emerald-600",
    rtp: 99.5,
    isLive: true,
    minBet: 1,
    maxBet: 5000,
    players: 189,
    rating: 4.8,
    tags: ["blackjack", "unlimited-players"],
  },
  {
    id: "l3",
    title: "Crazy Time",
    provider: "Evolution",
    category: "live-casino",
    thumbnail: "from-pink-900 to-fuchsia-500",
    rtp: 95.95,
    isLive: true,
    isHot: true,
    minBet: 0.1,
    maxBet: 1000,
    players: 621,
    rating: 4.9,
    tags: ["game-show", "multipliers"],
  },
  {
    id: "l4",
    title: "Baccarat Squeeze",
    provider: "Evolution",
    category: "live-casino",
    thumbnail: "from-blue-900 to-cyan-600",
    rtp: 98.94,
    isLive: true,
    minBet: 1,
    maxBet: 10000,
    players: 145,
    rating: 4.7,
    tags: ["baccarat", "squeeze"],
  },
  {
    id: "l5",
    title: "Dream Catcher",
    provider: "Evolution",
    category: "live-casino",
    thumbnail: "from-violet-900 to-violet-500",
    rtp: 96.58,
    isLive: true,
    minBet: 0.1,
    maxBet: 500,
    players: 287,
    rating: 4.7,
    tags: ["game-show", "wheel"],
  },
  {
    id: "l6",
    title: "Live Poker",
    provider: "Evolution",
    category: "poker",
    thumbnail: "from-red-900 to-red-500",
    rtp: 97.84,
    isLive: true,
    minBet: 1,
    maxBet: 10000,
    players: 93,
    rating: 4.8,
    tags: ["poker", "texas-holdem"],
  },
  // Table Games
  {
    id: "t1",
    title: "European Roulette",
    provider: "NetEnt",
    category: "table-games",
    thumbnail: "from-red-900 to-rose-600",
    rtp: 97.3,
    minBet: 0.1,
    maxBet: 10000,
    rating: 4.6,
    tags: ["roulette", "single-zero"],
  },
  {
    id: "t2",
    title: "Blackjack Classic",
    provider: "NetEnt",
    category: "table-games",
    thumbnail: "from-emerald-900 to-green-600",
    rtp: 99.28,
    minBet: 0.1,
    maxBet: 5000,
    rating: 4.7,
    tags: ["blackjack", "classic"],
  },
  {
    id: "t3",
    title: "3 Card Poker",
    provider: "Scientific Games",
    category: "table-games",
    thumbnail: "from-blue-900 to-sky-500",
    rtp: 96.63,
    minBet: 1,
    maxBet: 1000,
    rating: 4.5,
    tags: ["poker", "three-card"],
  },
  // Crash Games
  {
    id: "c1",
    title: "Aviator",
    provider: "Spribe",
    category: "crash",
    thumbnail: "from-sky-900 to-blue-500",
    rtp: 97,
    isHot: true,
    minBet: 0.1,
    maxBet: 100,
    players: 9850,
    rating: 4.9,
    tags: ["crash", "provably-fair"],
  },
  {
    id: "c2",
    title: "JetX",
    provider: "SmartSoft",
    category: "crash",
    thumbnail: "from-orange-900 to-red-600",
    rtp: 97,
    isNew: true,
    minBet: 0.1,
    maxBet: 300,
    players: 3210,
    rating: 4.7,
    tags: ["crash", "jet"],
  },
];

export const MOCK_PROMOTIONS: Promotion[] = [
  {
    id: "p1",
    title: "Welcome Package",
    description:
      "Get up to $3000 + 200 Free Spins across your first 4 deposits",
    image: "from-yellow-900 to-amber-600",
    type: "welcome",
    bonus: "Up to $3,000 + 200 FS",
    wagering: 35,
    isActive: true,
  },
  {
    id: "p2",
    title: "Weekend Reload",
    description: "Get a 50% reload bonus every weekend up to $500",
    image: "from-blue-900 to-blue-600",
    type: "reload",
    bonus: "50% up to $500",
    wagering: 30,
    expiry: "Every Weekend",
    isActive: true,
  },
  {
    id: "p3",
    title: "Cashback Monday",
    description: "Get 15% cashback on your losses every Monday",
    image: "from-green-900 to-green-600",
    type: "cashback",
    bonus: "15% Cashback",
    wagering: 5,
    expiry: "Every Monday",
    isActive: true,
  },
  {
    id: "p4",
    title: "Free Spins Friday",
    description: "50 free spins on selected slots every Friday with deposit",
    image: "from-purple-900 to-purple-600",
    type: "freespins",
    bonus: "50 Free Spins",
    wagering: 40,
    expiry: "Every Friday",
    isActive: true,
  },
  {
    id: "p5",
    title: "VIP High Roller",
    description:
      "Exclusive bonuses, dedicated manager & faster withdrawals for VIP players",
    image: "from-yellow-800 to-yellow-500",
    type: "vip",
    bonus: "Exclusive Perks",
    wagering: 0,
    isActive: true,
  },
  {
    id: "p6",
    title: "Refer a Friend",
    description:
      "Invite friends and earn $50 for each friend who deposits $20+",
    image: "from-pink-900 to-pink-600",
    type: "referral",
    bonus: "$50 per Referral",
    wagering: 20,
    isActive: true,
  },
];

export const MOCK_EVENTS: BettingEvent[] = [
  {
    id: "e1",
    sport: "Soccer",
    league: "UEFA Champions League",
    homeTeam: "Manchester City",
    awayTeam: "Real Madrid",
    startTime: "Today 20:45",
    isLive: true,
    odds: { home: 2.1, draw: 3.4, away: 3.2 },
    score: { home: 1, away: 1 },
  },
  {
    id: "e2",
    sport: "Soccer",
    league: "Premier League",
    homeTeam: "Arsenal",
    awayTeam: "Chelsea",
    startTime: "Tomorrow 17:30",
    isLive: false,
    odds: { home: 1.9, draw: 3.6, away: 3.8 },
  },
  {
    id: "e3",
    sport: "Basketball",
    league: "NBA",
    homeTeam: "LA Lakers",
    awayTeam: "Boston Celtics",
    startTime: "Today 23:00",
    isLive: true,
    odds: { home: 1.75, away: 2.05 },
    score: { home: 87, away: 92 },
  },
  {
    id: "e4",
    sport: "Tennis",
    league: "ATP Masters",
    homeTeam: "Novak Djokovic",
    awayTeam: "Carlos Alcaraz",
    startTime: "Today 15:00",
    isLive: false,
    odds: { home: 1.6, away: 2.3 },
  },
  {
    id: "e5",
    sport: "Soccer",
    league: "La Liga",
    homeTeam: "Barcelona",
    awayTeam: "Atletico Madrid",
    startTime: "Tomorrow 21:00",
    isLive: false,
    odds: { home: 1.85, draw: 3.5, away: 4.0 },
  },
  {
    id: "e6",
    sport: "MMA",
    league: "UFC 300",
    homeTeam: "Jon Jones",
    awayTeam: "Stipe Miocic",
    startTime: "Saturday 03:00",
    isLive: false,
    odds: { home: 1.45, away: 2.75 },
  },
  {
    id: "e7",
    sport: "Baseball",
    league: "MLB",
    homeTeam: "NY Yankees",
    awayTeam: "LA Dodgers",
    startTime: "Today 19:05",
    isLive: false,
    odds: { home: 1.95, away: 1.85 },
  },
  {
    id: "e8",
    sport: "Ice Hockey",
    league: "NHL",
    homeTeam: "Toronto Maple Leafs",
    awayTeam: "Montreal Canadiens",
    startTime: "Tomorrow 00:00",
    isLive: false,
    odds: { home: 1.7, draw: 4.5, away: 2.15 },
  },
];

export const VIP_LEVELS: VIPLevel[] = [
  {
    level: 1,
    name: "Bronze",
    minPoints: 0,
    maxPoints: 999,
    color: "#CD7F32",
    benefits: ["5% cashback", "Standard support", "Monthly bonus"],
    icon: "🥉",
    cashbackRate: 5,
  },
  {
    level: 2,
    name: "Silver",
    minPoints: 1000,
    maxPoints: 4999,
    color: "#C0C0C0",
    benefits: ["8% cashback", "Priority support", "Weekly bonus", "Free spins"],
    icon: "🥈",
    cashbackRate: 8,
  },
  {
    level: 3,
    name: "Gold",
    minPoints: 5000,
    maxPoints: 14999,
    color: "#FFD700",
    benefits: [
      "12% cashback",
      "24/7 support",
      "Daily bonus",
      "Higher limits",
      "Birthday gift",
    ],
    icon: "🥇",
    cashbackRate: 12,
  },
  {
    level: 4,
    name: "Platinum",
    minPoints: 15000,
    maxPoints: 49999,
    color: "#E5E4E2",
    benefits: [
      "15% cashback",
      "VIP manager",
      "Faster withdrawals",
      "Exclusive tournaments",
    ],
    icon: "💎",
    cashbackRate: 15,
  },
  {
    level: 5,
    name: "Diamond",
    minPoints: 50000,
    maxPoints: Infinity,
    color: "#B9F2FF",
    benefits: [
      "20% cashback",
      "Personal manager",
      "Same-day withdrawals",
      "Luxury gifts",
      "VIP events",
    ],
    icon: "👑",
    cashbackRate: 20,
  },
];

export const PAYMENT_METHODS = [
  { id: "visa", name: "Visa", icon: "💳", minDeposit: 10, maxDeposit: 50000, processingTime: "Instant" },
  { id: "mastercard", name: "Mastercard", icon: "💳", minDeposit: 10, maxDeposit: 50000, processingTime: "Instant" },
  { id: "bitcoin", name: "Bitcoin", icon: "₿", minDeposit: 10, maxDeposit: 100000, processingTime: "10-30 min" },
  { id: "ethereum", name: "Ethereum", icon: "Ξ", minDeposit: 10, maxDeposit: 100000, processingTime: "5-15 min" },
  { id: "skrill", name: "Skrill", icon: "💰", minDeposit: 10, maxDeposit: 20000, processingTime: "Instant" },
  { id: "neteller", name: "Neteller", icon: "💰", minDeposit: 10, maxDeposit: 20000, processingTime: "Instant" },
  { id: "bank", name: "Bank Transfer", icon: "🏦", minDeposit: 50, maxDeposit: 100000, processingTime: "1-3 days" },
];
